version: 2
jobs:
   build:
      machine:
         steps:
            - run: echo holi 
deployment:
   dev:
      branch: master
      commands:
         - ssh user1@10.131.137.223 'cd mvm-blockchain && git pull origin master'
